### ISSUE TITLE
App repeatedly crashes on WiFi fixed station settings

### ISSUE THREAD

**Issue by Marvin-1802** [kike-canaries/canairio_android#126]
**Describe the bug**
I was able to connect my device to WiFi using the app, but now each time I click on the _'WiFi fixed station settings'_ the app crashes.
I tried an uninstall/reinstall but the problem persist.  

_CanAirIO v0.7.5 rev594
Phone is an Moto G5 plus running AOS 8.1.0_

**Comment by Marvin-1802** [comment]
New information: 
I flashed the sketch to the ESP32 again, and was able to reconnect to wifi.  
The app seemed to be working ok after that, until I selected _Fixed tag location GeoHash_  and then clicked **set** _saving location_.  The app crashed and after this each time I select _WiFi fixed station settings_ the app crashes.

**Comment by hpsaturn** [comment]
Thanks a lot for your feedback and for wrote this report. I'm going tomorrow to try to find the crash in crashlytics. Meanwhile is possible maybe paste the information about your device, the `device info` section for example? Thanks.

**Comment by Marvin-1802** [comment]
Hello @hpsaturn 
Thank you for your reply.  Here is a screen shot of the device info page.

I also ran into another issue with my Heltec devices.  Two of the dev boards are rev.877 and one is rev.841.  The 841 doesn't show the wifi icon, but it appears to be enabled.  Should I create another bug report for this?

Also; I am not sure which pins on my Heltec ESP32 are enabled for CanAirio sensors.  I have a TDH11 sensor that I would like to to connect.  Any assistance would be greatly appreciated.  I am new to Arduino and ESP32.

![Canairo SS01](https://user-images.githubusercontent.com/96553443/148315539-4362d923-9371-47e1-9017-56643955db0f.png)

**Comment by hpsaturn** [comment]
> Hello @hpsaturn Thank you for your reply. Here is a screen shot of the device info page.
> 

Thanks

> I also ran into another issue with my Heltec devices. Two of the dev boards are rev.877 and one is rev.841. The 841 doesn't show the wifi icon, but it appears to be enabled. Should I create another bug report for this?
> 

it's weird because sounds like it doesn't has a right wifi connection. Maybe you can paste the log output? For that you can read how to do it [here](https://canair.io/docs/firmware_debugging.html) 

> Also; I am not sure which pins on my Heltec ESP32 are enabled for CanAirio sensors. I have a TDH11 sensor that I would like to to connect. Any assistance would be greatly appreciated. I am new to Arduino and ESP32.
> 

For that, the last wiring documentation is [here](https://github.com/kike-canaries/canairio_sensorlib#wiring). There say for Heltec for DHT11 the pin is 23 

https://github.com/kike-canaries/canairio_sensorlib/blob/master/src/Sensors.hpp#L19-L52

**Comment by Marvin-1802** [comment]
I installed from your web installer the 'test' version, and that seems to have corrected the issues with the Wi-Fi icon.  It is now running rev.879. . . I'm not exactly sure what that means :)

![Canario SS02](https://user-images.githubusercontent.com/96553443/148430587-7452e6ae-4083-43c5-b1e7-93855aca4f24.png) 

I have connected my DHT11 sensor to pin23 which appears to be working, however the Temp + Humidity information makes no sense to me.  Temp: 610 + Humidity: 420 (variable)

It is also having the same _Fixed tag location GeoHash_ problem.  The app crashes each time I select _WiFi fixed station setting_.

Also; my CanAirio's do not appear on your world map?

Thanks for all your help:)

**Comment by roberbike** [comment]
I have an Heltec board, and I have not your issues. The app works fine. Update the app to the last version on google store.
If the geohash is not saved into the board or there is not wifi, your station can not be see in the world map.

**Comment by hpsaturn** [comment]
Maybe the issue #127 it is relationed with this and location permission. @Marvin-1802  do you have all permissions granted that the app requested?

**Comment by Marvin-1802** [comment]
I have flashed the stable version again, and now it is rev.877  
It takes a long time to connect to wifi but the icon is present.

All permissions are granted.  As soon as I try to save the GeoStash the app crashes!?

**Comment by Marvin-1802** [comment]
I just installed the app on another phone, and connected to the device and same thing.  App crashes each time I select WiFi fixed station setting?!

**Comment by hpsaturn** [comment]
Is very weird that, the issue is relationed with your geohash, your location. One question, please doing the next steps:

- In Android, CanAirIO icon and in the `App Info -> clear data`
- Start again the app, pair, and record a mobile track with the record button in the chart section
- Grant the location and storage permissions
- Stop the track
- In the app: Settings->Fixed Station (if not crash here, please one screenshot of `Tag fixed location Geohash` switch

Thanks

**Comment by hpsaturn** [comment]
Meanwhile, the issue is here:

```java
    private void updateLocationSummary() {
        if (lastLocation != null) {
            SwitchPreference ifxdbSwitch = getInfluxDbSwitch();
            String summary = "";
            if (currentGeoHash.length() == 0 ) {
                summary = summary+"none.";
                ifxdbSwitch.setSummary(R.string.summary_ifx_nogeohash);
            }
            else {
                summary = summary + currentGeoHash;
                ifxdbSwitch.setSummary(R.string.key_enable_ifx_summary_ready);
                EasyPreference.Builder prefBuilder = AppData.getPrefBuilder(getContext());
                String name = currentGeoHash.substring(0,3);
                name = name + prefBuilder.getString(Keys.DEVICE_FLAVOR,"").substring(0,7);
                name = name + prefBuilder.getString(Keys.DEVICE_ADDRESS,"").substring(10);
                name = name.replace("_","");
                name = name.replace(":","");
                name = name.toUpperCase();
                name = getString(R.string.fixed_stations_map_summary)+"\nYour station: "+name;
                updateSummary(R.string.key_fixed_stations_map,name);
            }
            String geo = " (new: " + GeoHash.fromLocation(lastLocation, Config.GEOHASHACCU).toString()+")";
            summary = summary + geo;
            updateSummary(R.string.key_setting_enable_location,summary);
        }
```

In this line:
https://github.com/kike-canaries/canairio_android/blob/master/app/src/main/java/hpsaturn/pollutionreporter/view/SettingsFixedStation.java#L331

But it is impossible, because the validation of a geohash with size 0 is that. If the geohash for example is the size 1, and HELTEC is 6 chars is impossible the issue reported:

`Caused by java.lang.StringIndexOutOfBoundsException: length=6; index=7`

I don't know what happens here.

**Comment by Marvin-1802** [comment]
I recorded a track as you suggested, but the app crashes when I go to Fixed Station.

I should have mentioned this before, but didn't think it would matter.  
One phone I am using does not have a SIM card, I only get data via wifi and the other phone I am using has a SIM card but data via wifi only as well.  Perhaps this is the problem?

**Comment by hpsaturn** [comment]
Ok, thanks for your feedback. Nop, you don't need re-flash again the firmware. @roberbike already replicate your issue, and I'm going to free a new release for test a possible fix. Please wait some minutes and I will post the apk here.

**Comment by hpsaturn** [comment]
Ok, I don't have all things for replicate the issue in my environment, but maybe the next apk fix the issue:

http://influxdb.canair.io:8080/tmp/rev596v0.7.6_signed20220106.apk

Please let me know if it is right, and also @roberbike 

Thanks a lot guys for the help.

**Comment by roberbike** [comment]
After first test, it is working. It is fixed.

**Comment by Marvin-1802** [comment]
I installed the new APK v0.7.6 
That has corrected the crashing problem, but now when I click Geohash toggle and then click set, the Geohash toggle turns off each time?

**Comment by roberbike** [comment]
> I installed the new APK v0.7.6 That has corrected the crashing problem, but now when I click Geohash toggle and then click set, the Geohash toggle turns off each time?

Yes, it is normal. The geohash has been saved and on left side the  word none changued to geohash code.

**Comment by Marvin-1802** [comment]
Thanks for all your help! :)
I will see if I can sort out my temp/humi sensor and order other sensors.
I think that there must be something wrong with this particular ESP32, it takes forever to load and connect with wifi?!
I still don't see station on map, but I guess it could take sometime.

I don't know if you want/need more Canadian stations, but I will share your website with others to see if I can get others interested in your project.

**Comment by hpsaturn** [comment]
> Thanks for all your help! :) 

Thanks for report it and your feedback and tests.

> I will see if I can sort out my temp/humi sensor and order other sensors. 

Yes, please review the CanAirIO docs and CanAirIO sensorlib for the possible sensors supported. For example DHT11 is a very old sensor and it is very slow. We have supported others better than it.

> I think that there must be something wrong with this particular ESP32, it takes forever to load and connect with wifi?! I still don't see station on map, but I guess it could take sometime.

well, maybe is a problem with the antenna? also do you have the data icons blinking in your OLED screen? On the other hand, if you click in `CanAirIO Anaire` item in settins, this launch the browser with Temperature and Humidity widgets and the respective historics, and if you have a CO2 sensor, also for it.

[![CanAirIO CO2 easy Setup](https://github.com/kike-canaries/canairio_android/raw/master/images/anaire_youtube_preview.jpg)](https://youtu.be/29wfMPZXvps) 

(more short videos in [releases](https://github.com/kike-canaries/canairio_firmware/releases))

For the CanAirIO Worldmap you need a PM2.5 or CO2 sensor.

> I don't know if you want/need more Canadian stations, but I will share your website with others to see if I can get others interested in your project.

We need more help and more users, the Air Quality is a big problem in many countries. We need reach more founds, donations, documentation, activist, academics, etc all for improve the initiative.
